### ISSUE TITLE
SW2 DFU Mode

### ISSUE THREAD

**Issue by zukidog** [underverk/SmartWatch#13]
I am just getting started with looking in to firmware for SW2
I had been trying to get in to DFU mode many many times with no success.
I decided to try a different approach that seems much easier than all the descriptions I had been able to find that I wanted to share.
   -SW2 unplugged
   -turn on SW2
   -hold button until powers down and continue to hold button
   -while button held plug in USB to SW2
   -computer detected correctly WinUSB release button

Anything invalid with this approach?

**Comment by stg** [comment]
Not that I can see.
The method we use was described to us by Sony, but as long as you can get in it should be fine.
If you want you can add this to the github page that has instructions for entering DFU.

-STG

By reading this e-mail, you agree to not notice any spelling or grammatical errors that may or may not be present. Further, you agree to (unless otherwise specified) disclose the contents of this e-mail to anyone who may have an interest in the information. If you do not accept these terms you are obliged to delete this e-mail and any copies thereof before reaching the end of this paragraph.

From: zukidog 
Sent: Tuesday, November 12, 2013 4:19 AM
To: underverk/SmartWatch 
Subject: [SmartWatch] SW2 DFU Mode (#13)

I am just getting started with looking in to firmware for SW2
I had been trying to get in to DFU mode many many times with no success.
I decided to try a different approach that seems much easier than all the descriptions I had been able to find that I wanted to share.
SW2 unplugged
turn on SW2
hold button until powers down and continue to hold button
while button held plug in USB to SW2
computer detected correctly WinUSB release button

Anything invalid with this approach?
